/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { IQueryClientProvider, ISigningClientProvider, IMessageComposerProvider } from "./contractContextBase";
import { LsmStakingQueryClient } from "./LsmStaking.client";
import { LsmStakingClient } from "./LsmStaking.client";
import { LsmStakingMsgComposer } from "./LsmStaking.message-composer";
import { LsmStaking } from "./LsmStaking.provider";
import { ProposalOptionLockerQueryClient } from "./ProposalOptionLocker.client";
import { ProposalOptionLockerClient } from "./ProposalOptionLocker.client";
import { ProposalOptionLockerMsgComposer } from "./ProposalOptionLocker.message-composer";
import { ProposalOptionLocker } from "./ProposalOptionLocker.provider";
export interface IContractsContext {
  lsmStaking: IQueryClientProvider<LsmStakingQueryClient> & ISigningClientProvider<LsmStakingClient> & IMessageComposerProvider<LsmStakingMsgComposer>;
  proposalOptionLocker: IQueryClientProvider<ProposalOptionLockerQueryClient> & ISigningClientProvider<ProposalOptionLockerClient> & IMessageComposerProvider<ProposalOptionLockerMsgComposer>;
}
export const getProviders = (address?: string, cosmWasmClient?: CosmWasmClient, signingCosmWasmClient?: SigningCosmWasmClient) => ({
  lsmStaking: new LsmStaking({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }),
  proposalOptionLocker: new ProposalOptionLocker({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  })
});