/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./LsmStaking.types";
import * as _1 from "./LsmStaking.client";
import * as _2 from "./LsmStaking.message-composer";
import * as _3 from "./LsmStaking.react-query";
import * as _4 from "./LsmStaking.message-builder";
import * as _5 from "./LsmStaking.provider";
import * as _6 from "./ProposalOptionLocker.types";
import * as _7 from "./ProposalOptionLocker.client";
import * as _8 from "./ProposalOptionLocker.message-composer";
import * as _9 from "./ProposalOptionLocker.react-query";
import * as _10 from "./ProposalOptionLocker.message-builder";
import * as _11 from "./ProposalOptionLocker.provider";
import * as _12 from "./contractContextProviders";
import * as _13 from "./contractContextBase";
import * as _14 from "./contracts-context";
export namespace contracts {
  export const LsmStaking = { ..._0,
    ..._1,
    ..._2,
    ..._3,
    ..._4,
    ..._5
  };
  export const ProposalOptionLocker = { ..._6,
    ..._7,
    ..._8,
    ..._9,
    ..._10,
    ..._11
  };
  export const contractContextProviders = { ..._12
  };
  export const contractContextBase = { ..._13
  };
  export const contractsContext = { ..._14
  };
}