/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export type Uint128 = string;
export interface InstantiateMsg {
  locker_code_id: number;
  max_cap?: Uint128 | null;
  owner: string;
  staking_denom: string;
  validator: string;
}
export type ExecuteMsg = {
  deposit_lsm_shares: {};
} | {
  claim_rewards: {};
} | {
  deposit_rewards: {};
} | {
  withdraw: {
    amount: Uint128;
    validator: string;
  };
} | {
  update_config: {
    max_cap?: Uint128 | null;
    owner?: string | null;
  };
} | {
  create_voting_lockers: {
    proposal_id: number;
  };
} | {
  destroy_voting_lockers: {
    proposal_id: number;
  };
} | {
  return_lsm_shares: {
    proposal_id: number;
    vote_option: number;
  };
} | {
  rent_voting_power: {
    proposal_id: number;
    vote_option: number;
  };
};
export type QueryMsg = {
  config: {};
} | {
  staker_info: {
    address: string;
  };
} | {
  total_staked: {};
} | {
  reward_index: {};
} | {
  stakers: {
    limit?: number | null;
    start_after?: string | null;
  };
};
export type Decimal256 = string;
export type Addr = string;
export interface ConfigResponse {
  global_reward_index: Decimal256;
  is_paused: boolean;
  locker_code_id: number;
  max_cap?: Uint128 | null;
  owner: Addr;
  staking_denom: string;
  total_staked: Uint128;
  validator: string;
}
export interface RewardIndexResponse {
  global_reward_index: Decimal256;
}
export interface StakerInfoResponse {
  address: Addr;
  pending_rewards: Uint128;
  reward_index: Decimal256;
  staked_amount: Uint128;
}
export interface StakersResponse {
  stakers: StakerInfoResponse[];
}
export interface TotalStakedResponse {
  total_staked: Uint128;
}