/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { Uint128, InstantiateMsg, ExecuteMsg, QueryMsg, Decimal256, Addr, ConfigResponse, RewardIndexResponse, StakerInfoResponse, StakersResponse, TotalStakedResponse } from "./LsmStaking.types";
export interface LsmStakingMsg {
  contractAddress: string;
  sender: string;
  depositLsmShares: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  claimRewards: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  depositRewards: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  withdraw: ({
    amount,
    validator
  }: {
    amount: Uint128;
    validator: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  updateConfig: ({
    maxCap,
    owner
  }: {
    maxCap?: Uint128;
    owner?: string;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  createVotingLockers: ({
    proposalId
  }: {
    proposalId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  destroyVotingLockers: ({
    proposalId
  }: {
    proposalId: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  returnLsmShares: ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
  rentVotingPower: ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, _funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class LsmStakingMsgComposer implements LsmStakingMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.depositLsmShares = this.depositLsmShares.bind(this);
    this.claimRewards = this.claimRewards.bind(this);
    this.depositRewards = this.depositRewards.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.createVotingLockers = this.createVotingLockers.bind(this);
    this.destroyVotingLockers = this.destroyVotingLockers.bind(this);
    this.returnLsmShares = this.returnLsmShares.bind(this);
    this.rentVotingPower = this.rentVotingPower.bind(this);
  }

  depositLsmShares = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit_lsm_shares: {}
        })),
        funds: _funds
      })
    };
  };
  claimRewards = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          claim_rewards: {}
        })),
        funds: _funds
      })
    };
  };
  depositRewards = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit_rewards: {}
        })),
        funds: _funds
      })
    };
  };
  withdraw = ({
    amount,
    validator
  }: {
    amount: Uint128;
    validator: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          withdraw: {
            amount,
            validator
          }
        })),
        funds: _funds
      })
    };
  };
  updateConfig = ({
    maxCap,
    owner
  }: {
    maxCap?: Uint128;
    owner?: string;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_config: {
            max_cap: maxCap,
            owner
          }
        })),
        funds: _funds
      })
    };
  };
  createVotingLockers = ({
    proposalId
  }: {
    proposalId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_voting_lockers: {
            proposal_id: proposalId
          }
        })),
        funds: _funds
      })
    };
  };
  destroyVotingLockers = ({
    proposalId
  }: {
    proposalId: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          destroy_voting_lockers: {
            proposal_id: proposalId
          }
        })),
        funds: _funds
      })
    };
  };
  returnLsmShares = ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          return_lsm_shares: {
            proposal_id: proposalId,
            vote_option: voteOption
          }
        })),
        funds: _funds
      })
    };
  };
  rentVotingPower = ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, _funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          rent_voting_power: {
            proposal_id: proposalId,
            vote_option: voteOption
          }
        })),
        funds: _funds
      })
    };
  };
}