/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Uint128, InstantiateMsg, ExecuteMsg, QueryMsg, Decimal256, Addr, ConfigResponse, RewardIndexResponse, StakerInfoResponse, StakersResponse, TotalStakedResponse } from "./LsmStaking.types";
import { CamelCasedProperties } from "type-fest";
export abstract class LsmStakingExecuteMsgBuilder {
  static depositLsmShares = (): ExecuteMsg => {
    return {
      deposit_lsm_shares: ({} as const)
    };
  };
  static claimRewards = (): ExecuteMsg => {
    return {
      claim_rewards: ({} as const)
    };
  };
  static depositRewards = (): ExecuteMsg => {
    return {
      deposit_rewards: ({} as const)
    };
  };
  static withdraw = ({
    amount,
    validator
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    withdraw: unknown;
  }>["withdraw"]>): ExecuteMsg => {
    return {
      withdraw: ({
        amount,
        validator
      } as const)
    };
  };
  static updateConfig = ({
    maxCap,
    owner
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    update_config: unknown;
  }>["update_config"]>): ExecuteMsg => {
    return {
      update_config: ({
        max_cap: maxCap,
        owner
      } as const)
    };
  };
  static createVotingLockers = ({
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    create_voting_lockers: unknown;
  }>["create_voting_lockers"]>): ExecuteMsg => {
    return {
      create_voting_lockers: ({
        proposal_id: proposalId
      } as const)
    };
  };
  static destroyVotingLockers = ({
    proposalId
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    destroy_voting_lockers: unknown;
  }>["destroy_voting_lockers"]>): ExecuteMsg => {
    return {
      destroy_voting_lockers: ({
        proposal_id: proposalId
      } as const)
    };
  };
  static returnLsmShares = ({
    proposalId,
    voteOption
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    return_lsm_shares: unknown;
  }>["return_lsm_shares"]>): ExecuteMsg => {
    return {
      return_lsm_shares: ({
        proposal_id: proposalId,
        vote_option: voteOption
      } as const)
    };
  };
  static rentVotingPower = ({
    proposalId,
    voteOption
  }: CamelCasedProperties<Extract<ExecuteMsg, {
    rent_voting_power: unknown;
  }>["rent_voting_power"]>): ExecuteMsg => {
    return {
      rent_voting_power: ({
        proposal_id: proposalId,
        vote_option: voteOption
      } as const)
    };
  };
}
export abstract class LsmStakingQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static stakerInfo = ({
    address
  }: CamelCasedProperties<Extract<QueryMsg, {
    staker_info: unknown;
  }>["staker_info"]>): QueryMsg => {
    return {
      staker_info: ({
        address
      } as const)
    };
  };
  static totalStaked = (): QueryMsg => {
    return {
      total_staked: ({} as const)
    };
  };
  static rewardIndex = (): QueryMsg => {
    return {
      reward_index: ({} as const)
    };
  };
  static stakers = ({
    limit,
    startAfter
  }: CamelCasedProperties<Extract<QueryMsg, {
    stakers: unknown;
  }>["stakers"]>): QueryMsg => {
    return {
      stakers: ({
        limit,
        start_after: startAfter
      } as const)
    };
  };
}