/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { Uint128, InstantiateMsg, ExecuteMsg, QueryMsg, Decimal256, Addr, ConfigResponse, RewardIndexResponse, StakerInfoResponse, StakersResponse, TotalStakedResponse } from "./LsmStaking.types";
export interface LsmStakingReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  stakerInfo: ({
    address
  }: {
    address: string;
  }) => Promise<StakerInfoResponse>;
  totalStaked: () => Promise<TotalStakedResponse>;
  rewardIndex: () => Promise<RewardIndexResponse>;
  stakers: ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }) => Promise<StakersResponse>;
}
export class LsmStakingQueryClient implements LsmStakingReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.stakerInfo = this.stakerInfo.bind(this);
    this.totalStaked = this.totalStaked.bind(this);
    this.rewardIndex = this.rewardIndex.bind(this);
    this.stakers = this.stakers.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  stakerInfo = async ({
    address
  }: {
    address: string;
  }): Promise<StakerInfoResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      staker_info: {
        address
      }
    });
  };
  totalStaked = async (): Promise<TotalStakedResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_staked: {}
    });
  };
  rewardIndex = async (): Promise<RewardIndexResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      reward_index: {}
    });
  };
  stakers = async ({
    limit,
    startAfter
  }: {
    limit?: number;
    startAfter?: string;
  }): Promise<StakersResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      stakers: {
        limit,
        start_after: startAfter
      }
    });
  };
}
export interface LsmStakingInterface extends LsmStakingReadOnlyInterface {
  contractAddress: string;
  sender: string;
  depositLsmShares: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  claimRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  depositRewards: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  withdraw: ({
    amount,
    validator
  }: {
    amount: Uint128;
    validator: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  updateConfig: ({
    maxCap,
    owner
  }: {
    maxCap?: Uint128;
    owner?: string;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  createVotingLockers: ({
    proposalId
  }: {
    proposalId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  destroyVotingLockers: ({
    proposalId
  }: {
    proposalId: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  returnLsmShares: ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  rentVotingPower: ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class LsmStakingClient extends LsmStakingQueryClient implements LsmStakingInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.depositLsmShares = this.depositLsmShares.bind(this);
    this.claimRewards = this.claimRewards.bind(this);
    this.depositRewards = this.depositRewards.bind(this);
    this.withdraw = this.withdraw.bind(this);
    this.updateConfig = this.updateConfig.bind(this);
    this.createVotingLockers = this.createVotingLockers.bind(this);
    this.destroyVotingLockers = this.destroyVotingLockers.bind(this);
    this.returnLsmShares = this.returnLsmShares.bind(this);
    this.rentVotingPower = this.rentVotingPower.bind(this);
  }

  depositLsmShares = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_lsm_shares: {}
    }, fee, memo, _funds);
  };
  claimRewards = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      claim_rewards: {}
    }, fee, memo, _funds);
  };
  depositRewards = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_rewards: {}
    }, fee, memo, _funds);
  };
  withdraw = async ({
    amount,
    validator
  }: {
    amount: Uint128;
    validator: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      withdraw: {
        amount,
        validator
      }
    }, fee, memo, _funds);
  };
  updateConfig = async ({
    maxCap,
    owner
  }: {
    maxCap?: Uint128;
    owner?: string;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      update_config: {
        max_cap: maxCap,
        owner
      }
    }, fee, memo, _funds);
  };
  createVotingLockers = async ({
    proposalId
  }: {
    proposalId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      create_voting_lockers: {
        proposal_id: proposalId
      }
    }, fee, memo, _funds);
  };
  destroyVotingLockers = async ({
    proposalId
  }: {
    proposalId: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      destroy_voting_lockers: {
        proposal_id: proposalId
      }
    }, fee, memo, _funds);
  };
  returnLsmShares = async ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      return_lsm_shares: {
        proposal_id: proposalId,
        vote_option: voteOption
      }
    }, fee, memo, _funds);
  };
  rentVotingPower = async ({
    proposalId,
    voteOption
  }: {
    proposalId: number;
    voteOption: number;
  }, fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      rent_voting_power: {
        proposal_id: proposalId,
        vote_option: voteOption
      }
    }, fee, memo, _funds);
  };
}