/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { Uint128, InstantiateMsg, ExecuteMsg, QueryMsg, Decimal256, Addr, ConfigResponse, RewardIndexResponse, StakerInfoResponse, StakersResponse, TotalStakedResponse } from "./LsmStaking.types";
import { LsmStakingQueryClient } from "./LsmStaking.client";
export interface LsmStakingReactQuery<TResponse, TData = TResponse> {
  client: LsmStakingQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface LsmStakingStakersQuery<TData> extends LsmStakingReactQuery<StakersResponse, TData> {
  args: {
    limit?: number;
    startAfter?: string;
  };
}
export function useLsmStakingStakersQuery<TData = StakersResponse>({
  client,
  args,
  options
}: LsmStakingStakersQuery<TData>) {
  return useQuery<StakersResponse, Error, TData>(["lsmStakingStakers", client?.contractAddress, JSON.stringify(args)], () => client ? client.stakers({
    limit: args.limit,
    startAfter: args.startAfter
  }) : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface LsmStakingRewardIndexQuery<TData> extends LsmStakingReactQuery<RewardIndexResponse, TData> {}
export function useLsmStakingRewardIndexQuery<TData = RewardIndexResponse>({
  client,
  options
}: LsmStakingRewardIndexQuery<TData>) {
  return useQuery<RewardIndexResponse, Error, TData>(["lsmStakingRewardIndex", client?.contractAddress], () => client ? client.rewardIndex() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface LsmStakingTotalStakedQuery<TData> extends LsmStakingReactQuery<TotalStakedResponse, TData> {}
export function useLsmStakingTotalStakedQuery<TData = TotalStakedResponse>({
  client,
  options
}: LsmStakingTotalStakedQuery<TData>) {
  return useQuery<TotalStakedResponse, Error, TData>(["lsmStakingTotalStaked", client?.contractAddress], () => client ? client.totalStaked() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface LsmStakingStakerInfoQuery<TData> extends LsmStakingReactQuery<StakerInfoResponse, TData> {
  args: {
    address: string;
  };
}
export function useLsmStakingStakerInfoQuery<TData = StakerInfoResponse>({
  client,
  args,
  options
}: LsmStakingStakerInfoQuery<TData>) {
  return useQuery<StakerInfoResponse, Error, TData>(["lsmStakingStakerInfo", client?.contractAddress, JSON.stringify(args)], () => client ? client.stakerInfo({
    address: args.address
  }) : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface LsmStakingConfigQuery<TData> extends LsmStakingReactQuery<ConfigResponse, TData> {}
export function useLsmStakingConfigQuery<TData = ConfigResponse>({
  client,
  options
}: LsmStakingConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(["lsmStakingConfig", client?.contractAddress], () => client ? client.config() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}