/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient, SigningCosmWasmClient, ExecuteResult } from "@cosmjs/cosmwasm-stargate";
import { Coin, StdFee } from "@cosmjs/amino";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, Uint128, ConfigResponse, TotalVotingPowerResponse } from "./ProposalOptionLocker.types";
export interface ProposalOptionLockerReadOnlyInterface {
  contractAddress: string;
  config: () => Promise<ConfigResponse>;
  totalVotingPower: () => Promise<TotalVotingPowerResponse>;
}
export class ProposalOptionLockerQueryClient implements ProposalOptionLockerReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;

  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
    this.config = this.config.bind(this);
    this.totalVotingPower = this.totalVotingPower.bind(this);
  }

  config = async (): Promise<ConfigResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      config: {}
    });
  };
  totalVotingPower = async (): Promise<TotalVotingPowerResponse> => {
    return this.client.queryContractSmart(this.contractAddress, {
      total_voting_power: {}
    });
  };
}
export interface ProposalOptionLockerInterface extends ProposalOptionLockerReadOnlyInterface {
  contractAddress: string;
  sender: string;
  depositLsmShares: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
  destroy: (fee?: number | StdFee | "auto", memo?: string, _funds?: Coin[]) => Promise<ExecuteResult>;
}
export class ProposalOptionLockerClient extends ProposalOptionLockerQueryClient implements ProposalOptionLockerInterface {
  client: SigningCosmWasmClient;
  sender: string;
  contractAddress: string;

  constructor(client: SigningCosmWasmClient, sender: string, contractAddress: string) {
    super(client, contractAddress);
    this.client = client;
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.depositLsmShares = this.depositLsmShares.bind(this);
    this.destroy = this.destroy.bind(this);
  }

  depositLsmShares = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      deposit_lsm_shares: {}
    }, fee, memo, _funds);
  };
  destroy = async (fee: number | StdFee | "auto" = "auto", memo?: string, _funds?: Coin[]): Promise<ExecuteResult> => {
    return await this.client.execute(this.sender, this.contractAddress, {
      destroy: {}
    }, fee, memo, _funds);
  };
}