/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

export interface InstantiateMsg {
  manager: string;
  proposal_id: number;
  validator: string;
  vote_option: number;
}
export type ExecuteMsg = {
  deposit_lsm_shares: {};
} | {
  destroy: {};
};
export type QueryMsg = {
  config: {};
} | {
  total_voting_power: {};
};
export type Addr = string;
export type Uint128 = string;
export interface ConfigResponse {
  has_voted: boolean;
  manager: Addr;
  proposal_id: number;
  total_staked: Uint128;
  validator: string;
  vote_option: number;
}
export interface TotalVotingPowerResponse {
  total_staked: Uint128;
}