/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, Uint128, ConfigResponse, TotalVotingPowerResponse } from "./ProposalOptionLocker.types";
import { CamelCasedProperties } from "type-fest";
export abstract class ProposalOptionLockerExecuteMsgBuilder {
  static depositLsmShares = (): ExecuteMsg => {
    return {
      deposit_lsm_shares: ({} as const)
    };
  };
  static destroy = (): ExecuteMsg => {
    return {
      destroy: ({} as const)
    };
  };
}
export abstract class ProposalOptionLockerQueryMsgBuilder {
  static config = (): QueryMsg => {
    return {
      config: ({} as const)
    };
  };
  static totalVotingPower = (): QueryMsg => {
    return {
      total_voting_power: ({} as const)
    };
  };
}