/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { UseQueryOptions, useQuery } from "@tanstack/react-query";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, Uint128, ConfigResponse, TotalVotingPowerResponse } from "./ProposalOptionLocker.types";
import { ProposalOptionLockerQueryClient } from "./ProposalOptionLocker.client";
export interface ProposalOptionLockerReactQuery<TResponse, TData = TResponse> {
  client: ProposalOptionLockerQueryClient | undefined;
  options?: Omit<UseQueryOptions<TResponse, Error, TData>, "'queryKey' | 'queryFn' | 'initialData'"> & {
    initialData?: undefined;
  };
}
export interface ProposalOptionLockerTotalVotingPowerQuery<TData> extends ProposalOptionLockerReactQuery<TotalVotingPowerResponse, TData> {}
export function useProposalOptionLockerTotalVotingPowerQuery<TData = TotalVotingPowerResponse>({
  client,
  options
}: ProposalOptionLockerTotalVotingPowerQuery<TData>) {
  return useQuery<TotalVotingPowerResponse, Error, TData>(["proposalOptionLockerTotalVotingPower", client?.contractAddress], () => client ? client.totalVotingPower() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}
export interface ProposalOptionLockerConfigQuery<TData> extends ProposalOptionLockerReactQuery<ConfigResponse, TData> {}
export function useProposalOptionLockerConfigQuery<TData = ConfigResponse>({
  client,
  options
}: ProposalOptionLockerConfigQuery<TData>) {
  return useQuery<ConfigResponse, Error, TData>(["proposalOptionLockerConfig", client?.contractAddress], () => client ? client.config() : Promise.reject(new Error("Invalid client")), { ...options,
    enabled: !!client && (options?.enabled != undefined ? options.enabled : true)
  });
}