/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { Coin } from "@cosmjs/amino";
import { MsgExecuteContractEncodeObject } from "@cosmjs/cosmwasm-stargate";
import { MsgExecuteContract } from "cosmjs-types/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@cosmjs/encoding";
import { InstantiateMsg, ExecuteMsg, QueryMsg, Addr, Uint128, ConfigResponse, TotalVotingPowerResponse } from "./ProposalOptionLocker.types";
export interface ProposalOptionLockerMsg {
  contractAddress: string;
  sender: string;
  depositLsmShares: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
  destroy: (_funds?: Coin[]) => MsgExecuteContractEncodeObject;
}
export class ProposalOptionLockerMsgComposer implements ProposalOptionLockerMsg {
  sender: string;
  contractAddress: string;

  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.depositLsmShares = this.depositLsmShares.bind(this);
    this.destroy = this.destroy.bind(this);
  }

  depositLsmShares = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          deposit_lsm_shares: {}
        })),
        funds: _funds
      })
    };
  };
  destroy = (_funds?: Coin[]): MsgExecuteContractEncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          destroy: {}
        })),
        funds: _funds
      })
    };
  };
}