/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.35.7.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { ContractBase, IContractConstructor } from "./contractContextBase";
import { ProposalOptionLockerClient, ProposalOptionLockerQueryClient } from "./ProposalOptionLocker.client";
import { ProposalOptionLockerMsgComposer } from "./ProposalOptionLocker.message-composer";
export class ProposalOptionLocker extends ContractBase<ProposalOptionLockerClient, ProposalOptionLockerQueryClient, ProposalOptionLockerMsgComposer> {
  constructor({
    address,
    cosmWasmClient,
    signingCosmWasmClient
  }: IContractConstructor) {
    super(address, cosmWasmClient, signingCosmWasmClient, ProposalOptionLockerClient, ProposalOptionLockerQueryClient, ProposalOptionLockerMsgComposer);
  }

}